

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 120326hjj
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

async:
  executor:
    thread:
      corePoolSize: 8
      maxPoolSize: 8
      queueCapacity: 2000
      namePrefix: data-migrate-
